export const buttons = [
  {
    id: 1,
    title: "All",
    to: "/",
    category: "-1",
  },
  {
    id: 2,
    title: "Films",
    to: "/category?categoryId=1",
    category: "1",
  },
  {
    id: 3,
    title: "People",
    to: "/category?categoryId=22",
    category: "22",
  },
  {
    id: 4,
    title: "Comedy",
    to: "/category?categoryId=23",
    category: "23",
  },
  {
    id: 5,
    title: "Science",
    to: "/category?categoryId=28",
    category: "28",
  },
  {
    id: 6,
    title: "Entertainment",
    to: "/category?categoryId=24",
    category: "24",
  },
  {
    id: 7,
    title: "Autos & Vehicles",
    to: "/category?categoryId=2",
    category: "2",
  },
  {
    id: 8,
    title: "Pets & Animals",
    to: "/category?categoryId=15",
    category: "15",
  },
  {
    id: 9,
    title: "Music",
    to: "/category?categoryId=10",
    category: "10",
  },
  {
    id: 10,
    title: "Live",
    to: "/live",
    category: "11",
  },
  {
    id: 11,
    title: "Gaming",
    to: "/category?categoryId=20",
    category: "20",
  },
  {
    id: 12,
    title: "News",
    to: "/category?categoryId=25",
    category: "25",
  },
  {
    id: 13,
    title: "Sports",
    to: "/category?categoryId=17",
    category: "17",
  },
];
